---
- name: Setup Single Node Kubernetes Cluster (Optimized for Ansible 2.10)
  hosts: localhost
  connection: local
  become: yes

  vars:
    # Kubernetes version to install (e.g., v1.28)
    k8s_major_version: "v1.28"
    # Specific package version to install (Ensure this is available in the K8s repo)
    k8s_package_version: "1.28.10-1.1" 
    
    # Official Kubernetes repository URL
    k8s_repo_url: "https://pkgs.k8s.io/core:/stable:/{{ k8s_major_version }}/deb/" 
    
    # CNI (Calico) manifest URL (v3.27.0 is compatible with k8s v1.28)
    calico_manifest_url: "https://raw.githubusercontent.com/projectcalico/calico/v3.27.0/manifests/calico.yaml" 
    
    # Current user for setting file ownership of the kubeconfig
    ansible_current_user: "{{ lookup('env', 'USER') | default('root') }}"
    
  tasks:
    
    ## 1. Pre-setup: System Preparation (Compatibility Fixes)
    
    - name: Temporarily disable UFW (Uncomplicated Firewall) for setup
      community.general.ufw:
        state: disabled
      ignore_errors: yes 

    - name: Disable swap
      shell: swapoff -a
      when: ansible_swaptotal_mb > 0
    
    - name: Comment out swap entry in /etc/fstab
      replace:
        path: /etc/fstab
        regexp: '^(\s*[^#]+\s+swap\s+[^#]+)$'
        replace: '# \1'
        
    - name: Load 'br_netfilter' module (Prerequisite for Kubernetes networking)
      modprobe:
        name: br_netfilter
        state: present
    
    - name: Enable sysctl settings for Kubernetes networking
      sysctl:
        name: "{{ item.name }}"
        value: "{{ item.value }}"
        state: present
        reload: yes
      loop:
        - { name: 'net.bridge.bridge-nf-call-iptables', value: '1' }
        - { name: 'net.ipv4.ip_forward', value: '1' }
        
    ## 2. Install and Configure Container Runtime (Containerd)
    
    - name: Install required packages, including containerd
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg
        - lsb-release
        - containerd
    
    - name: Create /etc/containerd directory for config files
      file:
        path: /etc/containerd
        state: directory
        mode: '0755'

    - name: Generate default containerd config and enable systemd cgroup driver
      shell: | 
        containerd config default | sudo tee /etc/containerd/config.toml >/dev/null
        sed -i 's/SystemdCgroup = false/SystemdCgroup = true/g' /etc/containerd/config.toml

    - name: Restart and enable containerd service
      systemd:
        name: containerd
        state: restarted
        enabled: yes

    ## 3. Install Kubernetes Components (kubelet, kubeadm, kubectl)
    
    - name: Download Kubernetes GPG key and add to keyring
      shell: | 
        curl -fsSL {{ k8s_repo_url }}Release.key | sudo gpg --dearmor -o /etc/apt/keyrings/kubernetes-apt-keyring.gpg
      args:
        creates: /etc/apt/keyrings/kubernetes-apt-keyring.gpg
    
    - name: Add Kubernetes apt repository
      apt_repository:
        repo: "deb [signed-by=/etc/apt/keyrings/kubernetes-apt-keyring.gpg] {{ k8s_repo_url }} /"
        state: present
        filename: kubernetes
    
    - name: Install Kubernetes components (Using shell command for version pinning)
      shell: apt-get update && apt-get install -y kubelet={{ k8s_package_version }} kubeadm={{ k8s_package_version }} kubectl={{ k8s_package_version }}
      args:
        executable: /bin/bash

    - name: Start and enable kubelet
      systemd:
        name: kubelet
        state: started
        enabled: yes
        
    ## 4. Cluster Initialization and Configuration
    
    - name: Run kubeadm init to initialize the Kubernetes cluster
      shell: | 
        # Ignore both CPU count (NumCPU) and Memory (Mem) checks for low-spec VMs
        kubeadm init --pod-network-cidr=192.168.0.0/16 --cri-socket unix:///var/run/containerd/containerd.sock --ignore-preflight-errors=NumCPU,Mem
      args:
        creates: /etc/kubernetes/admin.conf
      register: kubeadm_init_result

    - name: Create .kube directory and set up ownership for kubectl access
      file:
        path: "/home/{{ ansible_current_user }}/.kube"
        state: directory
        mode: '0755'
        owner: "{{ ansible_current_user }}"
        group: "{{ ansible_current_user }}"
        
    - name: Copy kubeconfig file to the home directory
      copy:
        src: /etc/kubernetes/admin.conf
        dest: "/home/{{ ansible_current_user }}/.kube/config"
        remote_src: yes
        owner: "{{ ansible_current_user }}"
        group: "{{ ansible_current_user }}"
        mode: '0600'
        
    - name: Wait for API server to be available
      shell: |
        /usr/bin/kubectl --kubeconfig /etc/kubernetes/admin.conf get nodes
      register: kubectl_check
      until: kubectl_check.rc == 0
      retries: 40 
      delay: 5    
      changed_when: false
      failed_when: kubectl_check.rc != 0 and kubectl_check.attempts == 40

    ## 5. CNI and Single Node Configuration
    
    - name: Install CNI (Calico)
      shell: | 
        /usr/bin/kubectl apply -f {{ calico_manifest_url }}
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      args:
        executable: /bin/bash
        
    - name: Untaint the Master node to allow scheduling of Pods (Single-node setup)
      shell: | 
        /usr/bin/kubectl taint node {{ ansible_hostname }} node-role.kubernetes.io/control-plane:NoSchedule-
      environment:
        KUBECONFIG: /etc/kubernetes/admin.conf
      register: untaint_result
      changed_when: untaint_result.rc == 0
      ignore_errors: yes

    - name: Print completion message
      debug:
        msg: "Kubernetes cluster setup is complete! To use kubectl, run:\nexport KUBECONFIG=/home/{{ ansible_current_user }}/.kube/config\nOr log in with a new shell session."
